// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BkE-n5F1vVdhOH9R8InabsHfiaKxo-o',
    appId: '1:476439821296:android:ad69989de87fb06032bb35',
    messagingSenderId: '476439821296',
    projectId: 'teknovative-pravyatech',
    storageBucket: 'teknovative-pravyatech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuebiKxLEOIUHE20j-EOx0oBIuEFREwxo',
    appId: '1:476439821296:ios:c92e894f22bcc13332bb35',
    messagingSenderId: '476439821296',
    projectId: 'teknovative-pravyatech',
    storageBucket: 'teknovative-pravyatech.firebasestorage.app',
    iosBundleId: 'com.pravyatech.teknovativesolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuebiKxLEOIUHE20j-EOx0oBIuEFREwxo',
    appId: '1:476439821296:ios:c92e894f22bcc13332bb35',
    messagingSenderId: '476439821296',
    projectId: 'teknovative-pravyatech',
    storageBucket: 'teknovative-pravyatech.firebasestorage.app',
    iosBundleId: 'com.example.teknovativePravyatechApp',
  );

}
