// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukkTQc2p8dAhXeLuDWoxscxlNiqg0SP0',
    appId: '1:267874796422:web:b9c924b0cf13397a4f2207',
    messagingSenderId: '267874796422',
    projectId: 'teknovative-5e81b',
    authDomain: 'teknovative-5e81b.firebaseapp.com',
    storageBucket: 'teknovative-5e81b.firebasestorage.app',
    measurementId: 'G-WSEE31BM5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPdJ94Sc77y7Xrp0U8RDax4bYFe-0IUQ',
    appId: '1:267874796422:android:ea060041343d25294f2207',
    messagingSenderId: '267874796422',
    projectId: 'teknovative-5e81b',
    storageBucket: 'teknovative-5e81b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJuodhUxQk_WQuHG6jF9RQn7nX4iJAecs',
    appId: '1:267874796422:ios:a3870cdc572032574f2207',
    messagingSenderId: '267874796422',
    projectId: 'teknovative-5e81b',
    storageBucket: 'teknovative-5e81b.firebasestorage.app',
    iosBundleId: 'com.pravyatech.teknovativesolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJuodhUxQk_WQuHG6jF9RQn7nX4iJAecs',
    appId: '1:267874796422:ios:fc3f0421311617ee4f2207',
    messagingSenderId: '267874796422',
    projectId: 'teknovative-5e81b',
    storageBucket: 'teknovative-5e81b.firebasestorage.app',
    iosBundleId: 'com.example.teknovativePravyatechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCukkTQc2p8dAhXeLuDWoxscxlNiqg0SP0',
    appId: '1:267874796422:web:4113b4ce24c5f2974f2207',
    messagingSenderId: '267874796422',
    projectId: 'teknovative-5e81b',
    authDomain: 'teknovative-5e81b.firebaseapp.com',
    storageBucket: 'teknovative-5e81b.firebasestorage.app',
    measurementId: 'G-BSNFWLHFXQ',
  );

}